#pragma once

//From glfw3.h
#define DOVAH_MOUSE_BUTTON_1         0
#define DOVAH_MOUSE_BUTTON_2         1
#define DOVAH_MOUSE_BUTTON_3         2
#define DOVAH_MOUSE_BUTTON_4         3
#define DOVAH_MOUSE_BUTTON_5         4
#define DOVAH_MOUSE_BUTTON_6         5
#define DOVAH_MOUSE_BUTTON_7         6
#define DOVAH_MOUSE_BUTTON_8         7
#define DOVAH_MOUSE_BUTTON_LAST      DOVAH_MOUSE_BUTTON_8
#define DOVAH_MOUSE_BUTTON_LEFT      DOVAH_MOUSE_BUTTON_1
#define DOVAH_MOUSE_BUTTON_RIGHT     DOVAH_MOUSE_BUTTON_2
#define DOVAH_MOUSE_BUTTON_MIDDLE    DOVAH_MOUSE_BUTTON_3